### ISSUE TITLE
shield 2015 : écran noir

### ISSUE THREAD

**Issue by olivvv59** [mistertest/devtest#1]
bonjour,

après un petit test sur ma shield 2015 avec manette xbox one.

authentification nickel avec double authentification.
manette bien reconnue, on navigue bien dans les menus.

je lance un jeu.
je vois l'écran de chargement ( avec la fusée)
je vois le logo Xbox ( sur fond noir)
par contre, ensuite, j'entends la musique du jeu. mais l'écran reste noir ( je ne vois que 2 icônes en haut gauche : les 3 petits points + logo)

si je bricole avec la manette. j'entends que je navigue dans les menus. mais l'écran reste noir.

ma TV est une tv full hd.

voilà mon retour

**Comment by mistertest** [comment]
Essaye d'appuyer sur ok du remote ou faire un stick gauche enfoncé.  Quel est la version de  l'os sur la shield 2015  ?

**Comment by mistertest** [comment]
Penses aussi à mettre à jour le "ebview" en faisant une recherche sur le play store.

**Comment by olivvv59** [comment]
alors,
j'arrive à avoir l'image en faisant une petite manip.

lorsque j'ai l'écran noir.
j appuie sur le bouton Xbox de la manette.
je retourne dans le menu de la shield.
je retourne dans l'application.
et la, l'image s'affiche et je peux jouer.

je teste ce que vous avez dit.
et je vous laisse un retour

**Comment by olivvv59** [comment]
alors bien vu ... le webview n'était pas à jour.

l'image est vraiment plus sympa qu'avec l'application Android de Microsoft ( limité à 720p , il me semble)

j'ai aussi une 2017. je fais un petit test et je reviens vers vous. 

beau projet 👍

**Comment by mistertest** [comment]
> alors bien vu ... le webview n'était pas à jour.
> 
> l'image est vraiment plus sympa qu'avec l'application Android de Microsoft ( limité à 720p , il me semble)
> 
> j'ai aussi une 2017. je fais un petit test et je reviens vers vous.
> 
> beau projet 👍

**Comment by mistertest** [comment]
Ok nickel ça fera une pierre deux coups.

**Comment by olivvv59** [comment]
hello,

alors sur ma 2017, tout marche sauf le contrôle pendant le jeu.
c'est bizarre. il fonctionne bien dans le menu du shield, dans le menu du gamepass.
mais une fois, le jeu lancé ( l'image et son = ok), lorsqu'il demande : press button to start. je n'arrive pas à aller plus loin. 

le bouton central ( ou celui à gauche de celui ci) permet de revenir dans le menu du shield.
Les autres boutons ne font rien dans le jeu.  

je suis en version 8.2.3 pour la shield.

je vais voir ce que je peux trouver

**Comment by olivvv59** [comment]
j'ai trouvé le soucis.

sur cette Shield, dans les contrôleurs, j'ai une harmony keyboard ( pour contrôler la shield avec une télécommande harmony ) ... en la virant, ça fonctionne mieux.( mais du coup, je peux plus utiliser ma télécommande 😅)
le logiciel devait prendre celle par défaut en jeu. 

pour moi, ça me dérange pas. je ne vais pas jouer sur cette télévision.
mais ça peut poser problème. 😊

**Comment by olivvv59** [comment]
alors j'ai poussé mes tests.
si je. reassocie ma télécommande.

la manette continue de fonctionner.

par contre, à partir du moment où j'éteins le contrôleur et je le rallume.
celui passe en tant que 2 ème contrôleur et ne fonctionne plus.

**Comment by mistertest** [comment]
> j'ai trouvé le soucis.
> 
> sur cette Shield, dans les contrôleurs, j'ai une harmony keyboard ( pour contrôler la shield avec une télécommande harmony ) ... en la virant, ça fonctionne mieux.( mais du coup, je peux plus utiliser ma télécommande 😅)
> le logiciel devait prendre celle par défaut en jeu.
> 
> pour moi, ça me dérange pas. je ne vais pas jouer sur cette télévision.
> mais ça peut poser problème. 😊

Bonjour, 
Merci pour les tests.
Oui il faut une manette et une télécommande officielle connectée. J'ai aussi remarqué qu'en branchant un clavier la manette ne répondait plus.  Je ne pense pas, que je pourrais faire quelque chose là dessus, il faudra désactiver les devices incompatibles  pour utiliser l'app.
